version: "3.9"
services:
  jupyter:
    container_name: my-jupyter
    build: docker/jupyter
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ${HOME}/Documents/:/home/jovyan/work
